apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-gateway
  namespace: microservices-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-cloud-gateway
  template:
    metadata:
      labels:
        app: spring-cloud-gateway
    spec:
      containers:
        - name: spring-cloud-gateway
          image: your-docker-repo/spring-cloud-gateway:latest
          ports:
            - containerPort: 8080
