apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-1
  namespace: microservices-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-1
  template:
    metadata:
      labels:
        app: microservice-1
    spec:
      containers:
        - name: microservice-1
          image: your-docker-repo/microservice-1:latest
          ports:
            - containerPort: 8080
