apiVersion: v1
kind: Service
metadata:
  name: microservice-1
  namespace: microservices-namespace
spec:
  type: ClusterIP
  selector:
    app: microservice-1
  ports:
    - protocol: TCP
      port: 8080
