server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: microservice1-route
          uri: http://microservice-1.microservices-namespace.svc.cluster.local:8080
          predicates:
            - Path=/microservice1/**
        - id: microservice2-route
          uri: http://microservice-2.microservices-namespace.svc.cluster.local:8080
          predicates:
            - Path=/microservice2/**
